### ISSUE TITLE
Pretrained weight

### ISSUE THREAD

**Issue by Raven888888** [ChenyuGAO-CS/MobileCount#3]
Awesome paper!

May I know is the pretrained weights provided? (MC, MC x1.25 MC x2)
Where can I download them?

Thanks!

**Comment by Raven888888** [comment]
Found the links in the script. Will try it out. Thanks!

**Comment by SDarknessZX** [comment]
I need pretrained model， can you provide it to me？

**Comment by SDarknessZX** [comment]
> 
I need pretrained model， can you provide it to me？

**Comment by Raven888888** [comment]
@SDarknessZX [here](https://github.com/ChenyuGAO-CS/MobileCount/blob/master/models/MobileCount.py)
