### ISSUE TITLE
Not Exact the Same MobileNetV2 Structure

### ISSUE THREAD

**Issue by Yiming-M** [ChenyuGAO-CS/MobileCount#5]
Hi Chenyu,

Thanks for your great work. 

May I ask have you changed the number of output channels of each bottleneck? They look different from the original version of MobileNetV2. If so, that means you have to train the encoding part on the benchmark datasets (e.g. ShanghaiTech or UCF) right?

Many thanks,
Yiming

**Comment by ChenFan666** [comment]
> Hi Chenyu,
> 
> Thanks for your great work.
> 
> May I ask have you changed the number of output channels of each bottleneck? They look different from the original version of MobileNetV2. If so, that means you have to train the encoding part on the benchmark datasets (e.g. ShanghaiTech or UCF) right?
> 
> Many thanks, Yiming

i have the same question, because i use this code get the mae on SHB is only 14.1, can't achievement 9.1

**Comment by hosegragon** [comment]
Me

> > Hi Chenyu,
> > Thanks for your great work.
> > May I ask have you changed the number of output channels of each bottleneck? They look different from the original version of MobileNetV2. If so, that means you have to train the encoding part on the benchmark datasets (e.g. ShanghaiTech or UCF) right?
> > Many thanks, Yiming
> 
> i have the same question, because i use this code get the mae on SHB is only 14.1, can't achievement 9.1

Me too,because i use this code get the mae on UCF_CC_50 is only 362, can't achievement 321

**Comment by ChenyuGAO-CS** [comment]
Hi,

Implementation details can be found in my code. As for the difference of performance, I think it may be due to differences in versions of python, pyTorch, numpy, etc.

**Comment by hosegragon** [comment]
👍
